services:
  prometheus:
    image: prom/prometheus:v2.55.1
    command:
    # These 4 arguments are original found in the Dockerfile.
    # See https://github.com/prometheus/prometheus/blob/v2.55.1/Dockerfile#L25
    # Since we have to add extra arguments, we need to repeat them here.
    # See https://prometheus.io/docs/prometheus/latest/installation/#setting-command-line-parameters
    - "--config.file=/etc/prometheus/prometheus.yml"
    - "--storage.tsdb.path=/prometheus"
    - "--web.console.libraries=/usr/share/prometheus/console_libraries"
    - "--web.console.templates=/usr/share/prometheus/consoles"
    # Enable remote write
    - "--web.enable-remote-write-receiver"
    ports:
    - "9090:9090"

  otelcol-local:
    image: otel/opentelemetry-collector-contrib:0.120.0
    volumes:
    - ./otelcol-config.local.yaml:/etc/otelcol-contrib/config.yaml
    - ./ca.crt:/etc/otelcol-contrib/ca.crt
    - ./client.key:/etc/otelcol-contrib/client.key
    - ./client.crt:/etc/otelcol-contrib/client.crt
    ports:
    - "4318:4318"

  otelcol-remote:
    image: otel/opentelemetry-collector-contrib:0.120.0
    volumes:
    - ./otelcol-config.remote.yaml:/etc/otelcol-contrib/config.yaml
    - ./ca.crt:/etc/otelcol-contrib/ca.crt
    - ./server.crt:/etc/otelcol-contrib/server.crt
    - ./server.key:/etc/otelcol-contrib/server.key
