receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        tls:
          # Also load the system CA.
          # In actual deployment, the server certificate will be issued by
          # Let's encrypt.
          include_system_ca_certs_pool: true
          cert_file: /etc/otelcol-contrib/server.crt
          key_file: /etc/otelcol-contrib/server.key
          ca_file: /etc/otelcol-contrib/ca.crt

exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    tls:
      insecure: true
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite]
