receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

processors:
  attributes:
    actions:
    - key: deployment.environment.name
      value: local
      action: upsert

exporters:
  otlphttp:
    endpoint: https://otelcol-remote:4318
    tls:
      # Need to specify ca_file too,
      # otherwise, the client certificate will be considered as invalid.
      ca_file: /etc/otelcol-contrib/ca.crt
      # Also load the system CA.
      # In actual deployment, the server certificate will be issued by
      # Let's encrypt.
      include_system_ca_certs_pool: true
      cert_file: /etc/otelcol-contrib/client.crt
      key_file: /etc/otelcol-contrib/client.key

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [attributes]
      exporters: [otlphttp]
